---
.travis.yml:
  secure: "fH1bR1eBgA9tztMHtgdBSEOhNChC2YyoAczMzjUWgfDjinU1WOUPEprfV9upf6ZeQSTxAES36BBOrdxB6BVgdXlvLlCID+Lge1fTfi75ZX34q+eTadig/iZp3M0OveL2b5OmDv0cGbmMq8ywhgG+GPFuwPy7HF1Qjgul8UGNFOs="
  extras:
  - rvm: 2.4.0
    env: PUPPET_INSTALL_TYPE=agent PUPPET_VERSION="~> 4.0" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/debian-8
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty
  - rvm: 2.4.0
    env: PUPPET_INSTALL_TYPE=agent PUPPET_VERSION="~> 4.0" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/centos-7
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty
