language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
sudo: false
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.4.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.4.0" STRICT_VARIABLES=yes FUTURE_PARSER="yes"
notifications:
  email:
    - merritt@krakowitzer.com
script: bundle exec rake test
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "fH1bR1eBgA9tztMHtgdBSEOhNChC2YyoAczMzjUWgfDjinU1WOUPEprfV9upf6ZeQSTxAES36BBOrdxB6BVgdXlvLlCID+Lge1fTfi75ZX34q+eTadig/iZp3M0OveL2b5OmDv0cGbmMq8ywhgG+GPFuwPy7HF1Qjgul8UGNFOs="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3

